import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import WaveSvg from "@/assets/svg/WaveBlack";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KW Headless CMS",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="w-full h-[50px] z-10 absolute top-[62px]  min-[768px]:top-[68px]  xl:top-[72px]">
          <WaveSvg />
        </div>

        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
